version: '3.8'

services:
  app:
    build: 
      context: .
      target: production
    ports:
      - "8080:8080"
    restart: unless-stopped

  test:
    build:
      context: .
      target: test
    command: ng test --watch=false --browsers=ChromeHeadless
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped